"""01_initial_db

Revision ID: 75069fe98e13
Revises: 
Create Date: 2023-01-26 14:12:21.805226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75069fe98e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shorts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_short', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), server_default='f', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url_short')
    )
    op.create_index(op.f('ix_url_shorts_created_at'), 'url_shorts', ['created_at'], unique=False)
    op.create_table('url_statistics',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url_short', sa.String(length=256), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('client_host', sa.String(length=256), nullable=False),
    sa.Column('client_port', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_short'], ['url_shorts.url_short'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_statistics_used_at'), 'url_statistics', ['used_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_statistics_used_at'), table_name='url_statistics')
    op.drop_table('url_statistics')
    op.drop_index(op.f('ix_url_shorts_created_at'), table_name='url_shorts')
    op.drop_table('url_shorts')
    # ### end Alembic commands ###
