"""02_extension

Revision ID: 9247c158bd62
Revises: 103f76194ea1
Create Date: 2023-01-31 23:55:17.745453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9247c158bd62'
down_revision = '103f76194ea1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extension', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'extension')
    # ### end Alembic commands ###
