"""04_content_type

Revision ID: a4756082d01f
Revises: 69ab11d2e2c9
Create Date: 2023-01-30 23:38:57.465860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4756082d01f'
down_revision = '69ab11d2e2c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('content_type', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'content_type')
    # ### end Alembic commands ###
